export const FORM_SUBMIT_SUCCESS = "FORM_SUBMIT_SUCCESS"
export const FORM_SUBMIT_FAIL = "FORM_SUBMIT_FAIL"
export const FORM_SUBMIT_REQUEST = "FORM_SUBMIT_REQUEST"

export const USER_DATALIST_REQUEST = "USER_DATALIST_REQUEST";
export const USER_DATALIST_SUCCESS = "USER_DATALIST_SUCCESS";
export const USER_DATALIST_FAIL = "USER_DATALIST_FAIL";